title: Blog
email: your-email@example.com
description: >-
  Write an awesome description for your new site here.
baseurl: ""
url: "https://yanshangyun.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock